name: theFlowX AIDevOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  # Stage 1: Local Testing & Validation
  test:
    name: 🧪 Testing & Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Run Tests
      run: |
        echo "🔍 Running theFlowX test suite..."
        cp theflowx-package.json package.json
        npm run test
        
    - name: Validate HTML Structure
      run: |
        echo "📝 Validating HTML files..."
        find . -name "*.html" -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./bmad-method/*" | while read file; do
          if grep -q "<!DOCTYPE html>" "$file"; then
            echo "✅ $file - Valid HTML structure"
          else
            echo "❌ $file - Missing DOCTYPE"
            exit 1
          fi
        done
        
    - name: Check Asset Integrity
      run: |
        echo "🖼️  Checking asset files..."
        echo "CSS files: $(find assets/css -name "*.css" | wc -l)"
        echo "JS files: $(find assets/js -name "*.js" | wc -l)"
        echo "Images: $(find assets/img -type f | wc -l)"
        
    - name: Build for Production
      run: |
        echo "📦 Building for production..."
        npm run build

  # Stage 2: Staging Deployment (for testing)
  staging:
    name: 🎭 Staging Deployment
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Prepare Staging
      run: |
        echo "🧪 Preparing staging environment..."
        echo "📋 Files ready for staging deployment"
        echo "🔍 Would deploy to staging server for testing"
        echo "✅ Staging preparation complete"

  # Stage 3: Production Deployment (manual approval required)
  production:
    name: 🚀 Production Deployment
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: 
      name: production
      url: https://theflowx.com
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Final Production Check
      run: |
        echo "🔍 Final production readiness check..."
        cp theflowx-package.json package.json
        npm run build
        echo "✅ Production ready!"
        
    - name: Deploy to theflowx.com
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/README.md
          **/.github/**
          **/package*.json
          **/theflowx-package.json
          **/bmad-method/**
          **/.DS_Store
          **/test-*.sh
          **/DEPLOYMENT.md
          
    - name: Deployment Success
      run: |
        echo "🎉 SUCCESS! theFlowX.com deployment completed!"
        echo "🌐 Site URL: https://theflowx.com" 
        echo "⏰ Deployed at: $(date)"
        echo "📝 Commit: ${{ github.sha }}"